title: Service
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            import: details
          -
            handle: items
            field:
              collections:
                - products
              type: entries
              display: Items
          -
            handle: featured_image
            field:
              container: public
              folder: uploads
              allow_uploads: false
              type: assets
              display: featured_image
              max_files: 1
              mode: grid
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
              show_regenerate: true
