title: Service
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: items
            field:
              collections:
                - products
              type: entries
              display: Items
          -
            handle: featured_image
            field:
              container: assets
              allow_uploads: false
              type: assets
              display: 'Featured Image'
              max_files: 1
              mode: grid
          -
            handle: redirect_url
            field:
              type: text
              display: 'Redirect URL'
          -
            handle: redirect_url_text
            field:
              type: text
              display: 'Redirect URL Text'
          -
            handle: heading
            field:
              type: grid
              display: Heading
              fields:
                -
                  handle: title
                  field:
                    type: text
                    display: Title
                -
                  handle: description
                  field:
                    type: textarea
                    display: Description
                -
                  handle: featured_categories
                  field:
                    type: grid
                    display: 'Featured Categories'
                    fields:
                      -
                        handle: title
                        field:
                          type: text
                          display: Title
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
              show_regenerate: true
